# do not change these
TOPIC = "events"
WATERMARK_INTERVAL_MIN = 4

# you can change these
DELAY_PROB = 0.4
MAX_DELAY_SEC = 600
SPEEDUP_FACTOR = 600
NUM_PARTITIONS = 2 # of the kafka topic
RECOMMENDATION_CLIENTS = "100, 200, 300, 400, 500, 600, 700, 800, 900, 1000"
